# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"U\n\x0b\x43hatMessage\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x11\n\trecipient\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x12\n\nmessage_id\x18\x04 \x01(\x05\"\xd0\x01\n\x0b\x43hatRequest\x12\x1c\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x0c.chat.Action\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08passhash\x18\x03 \x01(\t\x12\r\n\x05user2\x18\x04 \x01(\t\x12\x0e\n\x06sender\x18\x05 \x01(\t\x12\x11\n\trecipient\x18\x06 \x01(\t\x12\x0f\n\x07message\x18\x07 \x01(\t\x12\x14\n\x0csent_message\x18\x08 \x01(\t\x12\x12\n\nn_messages\x18\t \x01(\x05\x12\x12\n\nmessage_id\x18\n \x01(\x05\"\xd4\x01\n\x0c\x43hatResponse\x12\x1c\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x0c.chat.Action\x12\x0e\n\x06result\x18\x02 \x01(\x08\x12\r\n\x05users\x18\x03 \x03(\t\x12\x15\n\rn_undelivered\x18\x04 \x01(\x05\x12#\n\x08messages\x18\x05 \x03(\x0b\x32\x11.chat.ChatMessage\x12\x12\n\nmessage_id\x18\x06 \x01(\x05\x12\x0e\n\x06sender\x18\x07 \x01(\t\x12\x14\n\x0csent_message\x18\x08 \x01(\t\x12\x11\n\tping_user\x18\t \x01(\t*\xba\x01\n\x06\x41\x63tion\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05LOGIN\x10\x01\x12\x0c\n\x08REGISTER\x10\x02\x12\x12\n\x0e\x43HECK_USERNAME\x10\x03\x12\r\n\tLOAD_CHAT\x10\x04\x12\x10\n\x0cSEND_MESSAGE\x10\x05\x12\x08\n\x04PING\x10\x06\x12\x14\n\x10VIEW_UNDELIVERED\x10\x07\x12\x12\n\x0e\x44\x45LETE_MESSAGE\x10\x08\x12\x12\n\x0e\x44\x45LETE_ACCOUNT\x10\t\x12\r\n\tPING_USER\x10\n2@\n\x0b\x43hatService\x12\x31\n\x04\x43hat\x12\x11.chat.ChatRequest\x1a\x12.chat.ChatResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTION']._serialized_start=534
  _globals['_ACTION']._serialized_end=720
  _globals['_CHATMESSAGE']._serialized_start=20
  _globals['_CHATMESSAGE']._serialized_end=105
  _globals['_CHATREQUEST']._serialized_start=108
  _globals['_CHATREQUEST']._serialized_end=316
  _globals['_CHATRESPONSE']._serialized_start=319
  _globals['_CHATRESPONSE']._serialized_end=531
  _globals['_CHATSERVICE']._serialized_start=722
  _globals['_CHATSERVICE']._serialized_end=786
# @@protoc_insertion_point(module_scope)
