# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"^\n\x0b\x43hatRequest\x12\x1c\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x0c.chat.Action\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0e\n\x06target\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"0\n\x0c\x43hatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t*Q\n\x06\x41\x63tion\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07\x43ONNECT\x10\x01\x12\x10\n\x0cSEND_MESSAGE\x10\x02\x12\x0e\n\nNOTIFY_ALL\x10\x03\x12\x0b\n\x07SEND_TO\x10\x04\x32@\n\x0b\x43hatService\x12\x31\n\x04\x43hat\x12\x11.chat.ChatRequest\x1a\x12.chat.ChatResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTION']._serialized_start=166
  _globals['_ACTION']._serialized_end=247
  _globals['_CHATREQUEST']._serialized_start=20
  _globals['_CHATREQUEST']._serialized_end=114
  _globals['_CHATRESPONSE']._serialized_start=116
  _globals['_CHATRESPONSE']._serialized_end=164
  _globals['_CHATSERVICE']._serialized_start=249
  _globals['_CHATSERVICE']._serialized_end=313
# @@protoc_insertion_point(module_scope)
